name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^2.0.0
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.4+2
  firebase_auth: ^0.15.5+2
  firebase_storage: ^3.1.1
  cloud_firestore: ^0.13.4




dev_dependencies:
  flutter_test:
    sdk: flutter
    

flutter:
  uses-material-design: true

  assets:
  - images/
